version: build-{build}
skip_tags: true
only_commits:
  files:
    - SqlWatch.Monitor/*
pull_requests:
  do_not_increment_build_number: true
max_jobs: 1
image: Visual Studio 2015
platform: x64
clone_folder: C:\projects\sqlwatch\
init:
- ps: >-
    <#
        .SYNOPSIS
            Set all installed instances of SQL server to dynamic ports
    #>

    Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\' |
        Where-Object {
            $_.Name -imatch 'MSSQL[_\d]+\.SQL.*'
        } |
        ForEach-Object {

            Write-Host "Setting $((Get-ItemProperty $_.PSPath).'(default)') to dynamic ports"
            Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpDynamicPorts -Value '0'
            Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpPort -Value ([string]::Empty)
        }
services:
- mssql2008r2sp2
- mssql2012sp1
- mssql2008r2sp2
- mssql2014
- mssql2016
- mssql2017
build_script:
- ps: C:\projects\sqlwatch\SQLWATCH-Build-Release.ps1
test_script:
- cmd: >-
    sqlpackage.exe /a:Publish /sf:C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\bin\Debug\SQLWATCH.dacpac /tdn:SQLWATCH /tsn:localhost\SQL2017

    sqlpackage.exe /a:Publish /sf:C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\bin\Debug\SQLWATCH.dacpac /tdn:SQLWATCH /tsn:localhost\SQL2016

    sqlpackage.exe /a:Publish /sf:C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\bin\Debug\SQLWATCH.dacpac /tdn:SQLWATCH /tsn:localhost\SQL2014

    sqlpackage.exe /a:Publish /sf:C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\bin\Debug\SQLWATCH.dacpac /tdn:SQLWATCH /tsn:localhost\SQL2012SP1
deploy: off